// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otvsjalqcwahtlgkvxil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90dnNqYWxxY3dhaHRsZ2t2eGlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwOTQzNDMsImV4cCI6MjA2MDY3MDM0M30.Voz5P6DpjdpduaDNI6BBzPhKfJjpolIBVwyDJz0V3BI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);